backend:
  name: github
  repo: terminaate/personal-site

media_folder: 'src/assets/images' # Location where files will be stored in the repo
public_folder: 'src/assets/images'

output:
  encode_file_path: true

collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/content/posts'
    extension: mdx
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - {
        label: 'Published',
        name: 'published',
        widget: 'boolean',
        default: true,
      }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'projects'
    label: 'Projects'
    folder: 'src/content/projects'
    extension: json
    editor:
      preview: false
    create: true
    format: json

    fields:
      - { label: 'Name', name: 'name', widget: 'string', allow_reorder: true }
      - { label: 'Description', name: 'description', widget: 'string', required: false }
      - { label: 'Github Link', name: 'githubLink', widget: 'string', required: false, type: 'url' }
      - { label: 'Link', name: 'link', widget: 'string', required: false, type: 'url' }
