backend:
  name: github
  repo: terminaate/personal-site

media_folder: 'src/assets/images' # Location where files will be stored in the repo
public_folder: 'src/assets/images'


collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/content/posts'
    extension: mdx
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - {
        label: 'Published',
        name: 'published',
        widget: 'boolean',
        default: true,
      }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
